services:
  - type: web
    name: student-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student-dashboard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: AUTH_SERVICE_BASE_URL
        value: https://auth-service-kaef.onrender.com
      - key: OAUTH_CLIENT_ID
        sync: false
      - key: OAUTH_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false

databases:
  - name: student-dashboard-db
    databaseName: student_dashboard
    user: student_dashboard
